name: C/C++ CI

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: if test -e ./configure; then ./configure; fi
    - name: make
      run: make
    - name: make check
      run: make check || echo "Make exited with non-zero error code."
    - name: make distcheck
      run: make distcheck || echo "Make exited with non-zero error code."
